[meta]
id = "rpgmakervxace"
name = "RPG Maker VX Ace"
category = "nwjs"
icon = "ri:window-line"
priority = 3

[detection]
min_score = 3

[[detection.optional]]
type = "file_exists"
path = "Game.exe"
weight = 2

[[detection.optional]]
type = "file_exists"
path = "Game"
weight = 2

[[detection.optional]]
type = "glob_match"
pattern = "RGSS3*.dll"
weight = 3

[[detection.required]]
type = "file_exists"
path = "Game.ini"

[launch]
strategy = "bottles"
entry_patterns = ["@native", "Game.exe"]
args = []
sandbox_home = true
