[meta]
id = "rpgmakermz"
name = "RPG Maker MZ"
category = "nwjs"
icon = "ri:window-line"
priority = 1

[detection]
min_score = 0

[[detection.required]]
type = "file_exists"
path = "js/rmmz_core.js"

[[detection.optional]]
type = "file_exists"
path = "js/rmmz_managers.js"
weight = 3

[[detection.required]]
type = "file_exists"
path = "data/System.json"

[[detection.optional]]
type = "file_exists"
path = "package.json"
weight = 1

[launch]
strategy = "nwjs"
runtime_id = "nwjs-sdk"
entry_patterns = []
args = ["--enable-webgl"]
sandbox_home = true
preserve_dirs = ["save", "www/save"]
