[meta]
id = "unity"
name = "Unity"
category = "other"
icon = "ri:gamepad-line"
priority = 5

[detection]
min_score = 0

[[detection.required]]
type = "file_exists"
path = "UnityPlayer.dll"

[[detection.required]]
type = "glob_match"
pattern = "*_Data"

[[detection.forbidden]]
type = "file_exists"
path = "Unity.exe"

[[detection.optional]]
type = "dir_exists"
path = "MonoBleedingEdge"
weight = 1

[[detection.optional]]
type = "file_exists"
path = "GameAssembly.dll"
weight = 1

[launch]
strategy = "bottles"
entry_patterns = ["@native", "*.exe"]
exclude_patterns = ["UnityCrashHandler*.exe", "UnityCrashHandler*"]
args = []
sandbox_home = true
preserve_dirs = ["Save", "Saves"]
