[meta]
id = "godot"
name = "Godot"
category = "other"
icon = "ri:gamepad-line"
priority = 6

[detection]
min_score = 0

[[detection.required]]
type = "has_extension"
ext = "pck"

[[detection.optional]]
type = "file_exists"
path = ".godot/global_script_class_cache.cfg"
weight = 2

[[detection.optional]]
type = "file_exists"
path = ".godot/extension_list.cfg"
weight = 2

[[detection.optional]]
type = "file_exists"
path = "project.godot"
weight = 2

[launch]
strategy = "bottles"
entry_patterns = ["@native", "*.exe"]
exclude_patterns = ["crashpad_handler.exe", "crashpad_handler*"]
args = []
sandbox_home = true
preserve_dirs = ["user", "save"]
