[meta]
id = "renpy"
name = "Ren'Py"
category = "renpy"
icon = "ri:slideshow-line"
priority = 0

[detection]
min_score = 0

[[detection.required]]
type = "dir_exists"
path = "renpy"

[[detection.optional]]
type = "has_native_executable"
weight = 3

[[detection.optional]]
type = "has_extension"
ext = "exe"
weight = 2

[[detection.required]]
type = "dir_exists"
path = "game"

[[detection.optional]]
type = "has_extension"
ext = "rpy"
weight = 3

[[detection.optional]]
type = "file_exists"
path = "game/script.rpy"
weight = 1

[[detection.optional]]
type = "glob_match"
pattern = "lib/python*"
weight = 1

[launch]
strategy = "bottles"
entry_patterns = ["@native", "*.sh", "*.exe"]
args = []
sandbox_home = true
